services:
  app:
    build: .
    volumes:
      - .:/home/node/app
    ports:
      - "3000:3000"

  email:
    image: mailhog/mailhog:latest
    platform: linux/amd64
    ports:
      - "8025:8025" # MailHog web UI
      - "1025:1025" # MailHog SMTP
